### ISSUE TITLE
H3:ODST BSP Splits Do Not Work

### ISSUE THREAD

**Issue by jonetiz** [Burnt-o/MCC_autosplitter#9]
Individual "Loading... done" splits no longer work on Season 8. This is likely due to the refactoring of the maps for flood firefight.

**Comment by jonetiz** [comment]
"halo3odst.dll"+01F2FFE8+50 seems to work better than the current variable **for the most part,** however peculiarly doesn't pick up on some Uplift Reserve loads.

**Comment by Cambidd** [comment]
Thanks for bringing this to my attention. Supprised it took this long for someone to notice. But I guess a lot of people run downpatched + odst not that popular. I have another solution which ideally shouldn't break when 343 recompile the dll. It broke because Burnts original implemenation used a ulong instead of a uint for some reason when the values in memory are clearly not spanning 8 bytes. They got rearranged when the dll got recompiled, hence shit broke.

**Comment by jonetiz** [comment]
> Thanks for bringing this to my attention. Supprised it took this long for someone to notice. But I guess a lot of people run downpatched + odst not that popular. I have another solution which ideally shouldn't break when 343 recompile the dll. It broke because Burnts original implemenation used a ulong instead of a uint for some reason when the values in memory are clearly not spanning 8 bytes. They got rearranged when the dll got recompiled, hence shit broke.

I mentioned the issue to Burnt a while ago, but we didn't discuss the final details. It *does* have more to do than just the dll recompile, as the BSP values have all changed, save for a single one. As I mentioned in this issue and #10 this is likely due to them changing the map files themselves.

**Comment by Cambidd** [comment]
![odstbsp](https://user-images.githubusercontent.com/95023823/186241358-4d2e63c4-0b12-4b65-ab4f-a28409b50bd3.png)
Same stuff, different spots. The problem came about because the original implementation was using an 8 byte memory watcher spanning over 2 4 byte vars in memory that got moved around.
